<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <RootNamespace>CK.AppIdentity</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.PerfectEvent" Version="27.0.0--ci.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CK.AppIdentity.Configuration\CK.AppIdentity.Configuration.csproj" />
    </ItemGroup>

</Project>
