<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <RootNamespace>CK.AppIdentity</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.PerfectEvent" Version="29.0.0-mike.0.ci.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CK.AppIdentity.Configuration\CK.AppIdentity.Configuration.csproj" />
    </ItemGroup>

</Project>
